# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ["R/**"]
  workflow_dispatch:

name: Document

jobs:
  document:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.3']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "roxygen2"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Document
        run: roxygen2::roxygenise()
        shell: Rscript {0}

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add man/\* NAMESPACE DESCRIPTION
          git commit -m "Update documentation" || echo "No changes to commit"
          # git pull --ff-only
          git push origin
