# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:

name: lint

jobs:
  lint:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.2.3']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "lintr"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Lint
        run: |
          lintr::lint_package()
        shell: Rscript {0}
